base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  username: root
  password: root

development:
  <<: *base
  database: onruby_development

caching:
  <<: *base
  database: onruby_caching

test:
  <<: *base
  database: onruby_test

production:
  <<: *base
  database: onruby_production
